# Generated by Django 4.2.4 on 2023-08-23 10:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biblioteka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('publisher', models.CharField(max_length=128)),
                ('date_of_buy', models.DateField(default=datetime.datetime(2023, 8, 23, 12, 24, 35, 635870))),
                ('status', models.IntegerField(choices=[(1, 'Nieprzeczytana'), (2, 'W trakcie czytania'), (3, 'Przeczytana')])),
                ('rating', models.FloatField()),
                ('review', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
