# Generated by Django 4.2.4 on 2023-09-21 00:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0004_planbooks_delete_user_alter_librarybooks_borrow_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ReadingPlanA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=64)),
                ('details', models.TextField()),
                ('goal', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='librarybooks',
            name='borrow_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 21, 2, 41, 47, 345241)),
        ),
        migrations.AlterField(
            model_name='mybook',
            name='date_of_buy',
            field=models.DateField(default=datetime.datetime(2023, 9, 21, 2, 41, 47, 344801)),
        ),
        migrations.AddField(
            model_name='readingplana',
            name='books',
            field=models.ManyToManyField(related_name='books', through='biblioteka.PlanBooks', to='biblioteka.mybook'),
        ),
        migrations.AddField(
            model_name='planbooks',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.mybook'),
        ),
        migrations.AddField(
            model_name='planbooks',
            name='reading_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.readingplana'),
        ),
    ]
