# Generated by Django 4.2.4 on 2023-09-21 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0005_planbooks_readingplana_remove_readingplan_books_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstobuy',
            name='book_status',
            field=models.IntegerField(choices=[(1, 'Kupiona'), (2, 'Niekupiona')], default=2),
        ),
        migrations.AlterField(
            model_name='librarybooks',
            name='borrow_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 21, 19, 8, 27, 549459)),
        ),
        migrations.AlterField(
            model_name='mybook',
            name='date_of_buy',
            field=models.DateField(default=datetime.datetime(2023, 9, 21, 19, 8, 27, 549108)),
        ),
    ]
