# Generated by Django 4.2.4 on 2023-09-21 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0006_remove_readingplan_books_delete_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstobuy',
            name='book_shop',
            field=models.IntegerField(choices=[(1, 'Null'), (2, 'Empik'), (3, 'Tania książka'), (4, 'Świat książki')], default=1),
        ),
        migrations.AlterField(
            model_name='librarybooks',
            name='borrow_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 21, 20, 0, 11, 762512)),
        ),
        migrations.AlterField(
            model_name='mybook',
            name='date_of_buy',
            field=models.DateField(default=datetime.datetime(2023, 9, 21, 20, 0, 11, 762163)),
        ),
    ]
