# Generated by Django 4.2.4 on 2023-09-22 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0007_remove_readingplan_books_delete_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstobuy',
            name='book_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='librarybooks',
            name='borrow_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 22, 15, 7, 0, 142814)),
        ),
        migrations.AlterField(
            model_name='mybook',
            name='date_of_buy',
            field=models.DateField(default=datetime.datetime(2023, 9, 22, 15, 7, 0, 142459)),
        ),
    ]
