# Generated by Django 4.2.4 on 2023-09-22 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka', '0008_remove_readingplan_books_delete_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarybooks',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='librarybooks',
            name='borrow_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 22, 17, 3, 41, 969164)),
        ),
        migrations.AlterField(
            model_name='mybook',
            name='date_of_buy',
            field=models.DateField(default=datetime.datetime(2023, 9, 22, 17, 3, 41, 968812)),
        ),
    ]
